# Generated by Django 3.0.3 on 2020-08-11 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='name',
            old_name='name',
            new_name='name_person',
        ),
        migrations.DeleteModel(
            name='CountryName',
        ),
    ]
